Update ibm provider 1.27.0
fortinet/ibm-fortigate-AP-HA-terraform-deploy pull request #6
Opened 2021-07-08 18:55 UTC by fshuva

- Update provider version to use 1.27.0
- Fixed typo for port3 and port4 interface names

2021-07-08 19:42 UTC, Joel-Cripps requested changes

2021-07-08 19:42 UTC, Joel-Cripps commented on instance.tf
>    }
I believe the typo needs to be fixed on both FortiGates.

2021-07-08 19:58 UTC, Joel-Cripps approved these changes

2021-07-13 18:15 UTC, jamie-pate approved these changes

2021-07-14 17:33 UTC, merged